
spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://db.qatbvihlttwgyarnskfn.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: .xJc!2Z2dmU*9jU
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG